### PR TITLE
Create Intent.ACTION for contact info click listeners

### PR DESCRIPTION
**Pull request by d-ben7**
When the user taps on the contact info, the appropriate Intent.ACTION will start. 
i.e. tapping on the contact phone will open the phone dialer.

### CODE REVIEW

**Comment by abunur** [comment]
Is this the PR for your Week 3 homework?

**Comment by abunur** [comment]
btw I suggest using a real profile photo for your GitHub account. Like LinkedIn, it's part of your online "resume", but in a very different sense. A real profile photo makes you more real in the eyes of a hiring manager.

**Comment by d-ben7** [comment]
Yes, this is my homework 3 PR. I had a previous PR, but I think I made a mistake of closing that PR to create this PR. I should have kept the original PR open?

I agree about the profile photo. I was messing around with the online logo maker but I couldn't find the option to upload an image. Thanks for the advice about LinkedIn.

**Comment by abunur** [comment]
> Yes, this is my homework 3 PR. I had a previous PR, but I think I made a mistake of closing that PR to create this PR. I should have kept the original PR open?
> 
> I agree about the profile photo. I was messing around with the online logo maker but I couldn't find the option to upload an image. Thanks for the advice about LinkedIn.

Yes you can create a single PR and continue to make commits and pushes and it will just update the PR, as long as it's the same branch. At the end, when the PR is approved (or in our case, graded) then you can merge the PR and it will merge to whatever branch you created the PR against. Typically in a real scenario we have a feature branch that gets merged back to develop branch when the PR is approved.

Nice job on the homework. Very clean design and clean code as well. I don't really have any critiques on your code this round.

Also great job implementing separate layout for landscape view.

Your grade for this exercise is "above and beyond" 👍

**Pull request merged**
